* #34 fix tls issue with db 7.1.1 (#35)
* * #34 fix tls issue with db 7.1.1

* * #34 add golang 1.17

* #34: Run sonar only for default go and db versions

* #34: Upgrade build to latest 7.0.x

* Enable caching and remove unsupported go versions

* #34: Add release notes entry

* #34: Reduce duplicate code in integration test

* Upgrade dependencies

* #34: Remove caching (already included in golangci-lint

https://github.com/golangci/golangci-lint-action#performance

* Add integration test with UseTLS(true)

* #34 Improve layout of README.md

* #34: Improve layout of code examples

* Revert change to lint version

  Running [/home/runner/golangci-lint-1.42.1-linux-amd64/golangci-lint run --out-format=github-actions] in [] ...
  level=error msg="Running error: context loading failed: no go files to analyze"

  Error: golangci-lint exit with code 5
  Ran golangci-lint in 879ms

* #34: Update go to minimum supported version

* Use hostname from testcontainer instead of localhost

* Update release date

* Add integrationtests for compression

Co-authored-by: Christoph Pirkl <christoph.pirkl@exasol.com>