Revert change to lint version
  Running [/home/runner/golangci-lint-1.42.1-linux-amd64/golangci-lint run --out-format=github-actions] in [] ...
  level=error msg="Running error: context loading failed: no go files to analyze"

  Error: golangci-lint exit with code 5
  Ran golangci-lint in 879ms